services:
  - type: web
    name: tableau-dashboard-app
    env: python
    plan: free
    pythonVersion: "3.11.9"
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn main:app
